apiVersion: v1
kind: Pod
metadata:
  name: test-pod-4
spec:
  containers:
  - name: test-app
    image: nginx
    volumeMounts:
    - mountPath: "/data"
      name: ebs-volume
  volumes:
  - name: ebs-volume
    persistentVolumeClaim:
      claimName: test-pvc-4

